modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "${github_url}/issues"
license = "${license}"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
authors = "${author}"
description = '''
${description}
'''
logoFile = "icon.png"

[[dependencies.reaping]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.reaping]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.reaping]]
modId = "architectury"
mandatory = true
versionRange = "[4.2.50,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.reaping]]
modId = "cloth_config"
mandatory = true
versionRange = "[1.0.0,]"
